export const VERSION = "v1.3.0"

export const URL_EPC_ALL = `/api/epc`
export const URL_EPC = `/api/epc?`
export const URL_TERMINAL = `/api/terminal`

export const BLOCK_3F_A = "A-3F 成品區"
export const BLOCK_3F_B = "B-3F 成品區"
export const BLOCK_2F_A = "A-2F 成品區"
export const BLOCK_1F_TEMP = "A-1F 暫存區"
export const BLOCK_1F = "1F 緩衝區"
export const BLOCK_A = "A"
export const BLOCK_B = "B"
export const BLOCK_C = "C"
export const BLOCK_D = "D"
export const BLOCK_E = "E"
export const BLOCK_F = "F"
export const BLOCK_G = "G"
export const BLOCK_H = "H"
export const BLOCK_I = "I"
export const NAV_WAREHOUSE = "倉庫"
export const NAV_TERMINAL = "已出貨"
export const NAV_HOME = "首頁"
export const NAV_TITLE = "儲位目視化管理看板"
export const NAV_SETTING = "設定"

export const LIMIT = "警示棧板數量上限"
export const CANCEL = "取消"
export const SAVE = "儲存"
export const SELECT = "選擇"
export const SEARCH = "查詢"
export const CANCELSEARCH = "取消查詢"
export const FORM_IDLE = "閒置時間"
export const FORM_CAROUSEL = "圖片跳轉"
export const FORM_VERSION = "版本資訊"

export const ERROR = "查詢錯誤"
export const CLOSE = "關閉"
export const MOVE = "移至已出貨"
export const RECOVER = "返回原位置"
export const CONFIRM = "確定"

export const TH_LINE = "線別"
export const TH_TASKNO = "工單"
export const TH_PN = "料號"
export const TH_QTY = "數量"
export const TH_PALLET = "棧板ID"
export const TH_TIME = "時間"
export const TH_PALLET_TRACE = "單板移動軌跡追蹤"
export const NOW = "現在"

export const _3A_modal_target = "threeAModalTarget"
export const _2A_modal_target = "twoAModalTarget"
export const _3B_modal_target = "threeBModalTarget"
export const _search_modal_target = "searchModalTarget"
export const _timeline_modal_target = "timelineModalTarget"
export const _setting_modal_target = "settingModalTarget"
export const _move_modal_target = "moveModalTarget"
export const _recover_modal_target = "recoverModalTarget"

export const SELECT_0 = "永不"
export const SELECT_5 = "5秒"
export const SELECT_10 = "10秒"
export const SELECT_30 = "30秒"
export const SELECT_60 = "1分鐘"
export const SELECT_300 = "5分鐘"
export const SELECT_600 = "10分鐘"
export const SELECT_900 = "15分鐘"
export const SELECT_1800 = "30分鐘"
export const SELECT_3600 = "1小時"
export const SELECT_7200 = "2小時"
